import type { TFunction } from "@/shared/i18n";
import type { ListViewFieldDataType } from "@/shared/ui/list-view/listViewConfig";
import type {
  ListViewFieldSourceType,
  ListViewPerformanceCost,
  ListViewRendererType,
} from "@/shared/ui/list-view/listViewConfig/types";
import type { EmployeeListRow } from "./employeeListRowModel";

export type EmployeesTableFilterKind = "text" | "boolean" | "enum" | "date" | "none";

export type EmployeesTableColumnSchema = {
  id: string;
  label: string;
  accessorKey?: keyof EmployeeListRow;
  dataType: ListViewFieldDataType;
  sourceType: ListViewFieldSourceType;
  defaultVisible: boolean;
  lockedVisible: boolean;
  sortable: boolean;
  filterable: boolean;
  exportable: boolean;
  selectable: boolean;
  defaultSize?: number;
  minSize?: number;
  maxSize?: number;
  defaultFlex?: number;
  rendererType: ListViewRendererType;
  performanceCost: ListViewPerformanceCost;
  filterKind: EmployeesTableFilterKind;
  /** For enum filters — stable row values */
  enumField?: keyof EmployeeListRow;
};

type BuildEmployeesTableSchemaInput = {
  t: TFunction;
};

function textCol(
  input: BuildEmployeesTableSchemaInput,
  id: keyof EmployeeListRow & string,
  labelKey: string,
  defaultVisible: boolean,
  extra?: Partial<EmployeesTableColumnSchema>,
): EmployeesTableColumnSchema {
  return {
    id,
    label: input.t(labelKey),
    accessorKey: id,
    dataType: "string",
    sourceType: "document",
    defaultVisible,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    performanceCost: "low",
    filterKind: "text",
    ...extra,
  };
}

function dateCol(
  input: BuildEmployeesTableSchemaInput,
  id: keyof EmployeeListRow & string,
  labelKey: string,
  defaultVisible: boolean,
  extra?: Partial<EmployeesTableColumnSchema>,
): EmployeesTableColumnSchema {
  return {
    id,
    label: input.t(labelKey),
    accessorKey: id,
    dataType: "date",
    sourceType: "document",
    defaultVisible,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "date",
    performanceCost: "low",
    filterKind: "date",
    defaultSize: 118,
    ...extra,
  };
}

export function buildEmployeesTableSchema(input: BuildEmployeesTableSchemaInput): EmployeesTableColumnSchema[] {
  const { t } = input;
  return [
    {
      id: "lineNo",
      label: t("doc.columns.lineNo"),
      dataType: "identifier",
      sourceType: "system",
      defaultVisible: true,
      lockedVisible: true,
      sortable: false,
      filterable: false,
      exportable: true,
      selectable: true,
      defaultSize: 56,
      minSize: 56,
      maxSize: 56,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "none",
    },
    {
      id: "employeeCode",
      label: t("employees.list.columns.employeeCode"),
      accessorKey: "employeeCode",
      dataType: "identifier",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 120,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
    },
    {
      id: "fullName",
      label: t("employees.list.columns.fullName"),
      accessorKey: "fullName",
      dataType: "string",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      minSize: 160,
      defaultFlex: 1,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
    },
    {
      id: "status",
      label: t("employees.list.columns.status"),
      accessorKey: "status",
      dataType: "enum",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 110,
      rendererType: "status-badge",
      performanceCost: "low",
      filterKind: "enum",
      enumField: "status",
    },
    {
      id: "departmentCode",
      label: t("employees.list.columns.department"),
      accessorKey: "departmentCode",
      dataType: "string",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 120,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
    },
    {
      id: "positionCode",
      label: t("employees.list.columns.position"),
      accessorKey: "positionCode",
      dataType: "string",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 140,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
    },
    {
      id: "employmentType",
      label: t("employees.list.columns.employmentType"),
      accessorKey: "employmentType",
      dataType: "enum",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 130,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "enum",
      enumField: "employmentType",
    },
    {
      id: "workSchedule",
      label: t("employees.list.columns.workSchedule"),
      accessorKey: "workSchedule",
      dataType: "enum",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 120,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "enum",
      enumField: "workSchedule",
    },
    {
      id: "managerDisplay",
      label: t("employees.list.columns.manager"),
      accessorKey: "managerDisplay",
      dataType: "string",
      sourceType: "derived",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 130,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
    },
    {
      id: "displayName",
      label: t("employees.list.columns.displayName"),
      accessorKey: "displayName",
      dataType: "string",
      sourceType: "document",
      defaultVisible: false,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 120,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
    },
    textCol(input, "personnelNumber", "employees.list.columns.personnelNumber", false, { defaultSize: 120 }),
    dateCol(input, "employmentStartDate", "employees.list.columns.employmentStartDate", false),
    dateCol(input, "employmentEndDate", "employees.list.columns.employmentEndDate", false),
    textCol(input, "comment", "employees.list.columns.comment", false, { minSize: 200, defaultFlex: 1, defaultSize: 220 }),
    dateCol(input, "dateOfBirth", "employees.list.columns.dateOfBirth", false),
    {
      id: "gender",
      label: t("employees.list.columns.gender"),
      accessorKey: "gender",
      dataType: "enum",
      sourceType: "document",
      defaultVisible: false,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 110,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "enum",
      enumField: "gender",
    },
    textCol(input, "citizenship", "employees.list.columns.citizenship", false, { defaultSize: 72 }),
    textCol(input, "iin", "employees.list.columns.iin", false, { defaultSize: 120 }),
    textCol(input, "placeOfBirth", "employees.list.columns.placeOfBirth", false, { minSize: 140 }),
    textCol(input, "maritalStatus", "employees.list.columns.maritalStatus", false, { defaultSize: 120 }),
    textCol(input, "personalPhone", "employees.list.columns.personalPhone", false, { defaultSize: 130 }),
    textCol(input, "personalEmail", "employees.list.columns.personalEmail", false, { defaultSize: 180 }),
    textCol(input, "emergencyContactName", "employees.list.columns.emergencyContactName", false, { minSize: 140 }),
    textCol(input, "emergencyContactPhone", "employees.list.columns.emergencyContactPhone", false, {
      defaultSize: 130,
    }),
    {
      id: "documentType",
      label: t("employees.list.columns.documentType"),
      accessorKey: "documentType",
      dataType: "enum",
      sourceType: "document",
      defaultVisible: false,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 160,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "enum",
      enumField: "documentType",
    },
    textCol(input, "documentNumber", "employees.list.columns.documentNumber", false, { defaultSize: 130 }),
    textCol(input, "issuingAuthority", "employees.list.columns.issuingAuthority", false, { minSize: 160 }),
    dateCol(input, "issueDate", "employees.list.columns.issueDate", false),
    dateCol(input, "expiryDate", "employees.list.columns.expiryDate", false),
    textCol(input, "country", "employees.list.columns.country", false, { defaultSize: 88 }),
    textCol(input, "region", "employees.list.columns.region", false, { defaultSize: 120 }),
    textCol(input, "city", "employees.list.columns.city", false, { defaultSize: 120 }),
    textCol(input, "residentialAddress", "employees.list.columns.residentialAddress", false, {
      minSize: 200,
      defaultFlex: 1,
      defaultSize: 220,
    }),
    textCol(input, "registrationAddress", "employees.list.columns.registrationAddress", false, {
      minSize: 200,
      defaultFlex: 1,
      defaultSize: 220,
    }),
    {
      id: "functionalManagerDisplay",
      label: t("employees.list.columns.functionalManager"),
      accessorKey: "functionalManagerDisplay",
      dataType: "string",
      sourceType: "derived",
      defaultVisible: false,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 140,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
    },
    textCol(input, "teamOrGroup", "employees.list.columns.teamOrGroup", false, { defaultSize: 140 }),
    textCol(input, "responsibilityZone", "employees.list.columns.responsibilityZone", false, { minSize: 160 }),
    textCol(input, "shiftLabel", "employees.list.columns.shiftCrew", false, { defaultSize: 130 }),
    textCol(input, "workEmail", "employees.list.columns.workEmail", false, { defaultSize: 200 }),
    textCol(input, "workPhone", "employees.list.columns.workPhone", false, { defaultSize: 130 }),
    textCol(input, "internalExtension", "employees.list.columns.internalExtension", false, { defaultSize: 100 }),
    textCol(input, "corporateMessengerId", "employees.list.columns.corporateMessengerId", false, {
      defaultSize: 160,
    }),
    textCol(input, "officeLocation", "employees.list.columns.officeLocation", false, { minSize: 160 }),
  ];
}
