import type { TFunction } from "@/shared/i18n";
import type { ListViewFieldDataType } from "@/shared/ui/ag-grid/listViewConfig";
import type {
  ListViewFieldSourceType,
  ListViewPerformanceCost,
  ListViewRendererType,
} from "@/shared/ui/ag-grid/listViewConfig/types";

export type MarkdownJournalTableFilterKind = "text" | "enum" | "number" | "datetime" | "none";
export type MarkdownJournalTableFormatKind =
  | "none"
  | "plain"
  | "journal-status"
  | "markdown-price";

export type MarkdownJournalTanstackColumnSchema = {
  id: string;
  label: string;
  accessorKey?: string;
  dataType: ListViewFieldDataType;
  sourceType: ListViewFieldSourceType;
  defaultVisible: boolean;
  lockedVisible: boolean;
  sortable: boolean;
  filterable: boolean;
  exportable: boolean;
  selectable: boolean;
  defaultSize?: number;
  minSize?: number;
  maxSize?: number;
  rendererType: ListViewRendererType;
  performanceCost: ListViewPerformanceCost;
  filterKind: MarkdownJournalTableFilterKind;
  formatKind?: MarkdownJournalTableFormatKind;
  cellDataType?: boolean;
};

export function buildMarkdownJournalsTableSchema(input: { t: TFunction }): MarkdownJournalTanstackColumnSchema[] {
  const { t } = input;
  return [
    {
      id: "lineNo",
      label: t("doc.columns.lineNo"),
      dataType: "identifier",
      sourceType: "system",
      defaultVisible: true,
      lockedVisible: true,
      sortable: false,
      filterable: false,
      exportable: true,
      selectable: true,
      defaultSize: 56,
      minSize: 56,
      maxSize: 56,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "none",
    },
    {
      id: "number",
      label: t("doc.columns.number"),
      accessorKey: "number",
      dataType: "identifier",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 170,
      minSize: 150,
      maxSize: 260,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
      formatKind: "plain",
    },
    {
      id: "status",
      label: t("common.status"),
      accessorKey: "status",
      dataType: "enum",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 130,
      minSize: 120,
      maxSize: 200,
      rendererType: "status-badge",
      performanceCost: "low",
      filterKind: "enum",
      formatKind: "journal-status",
    },
    {
      id: "sourceWarehouseLabel",
      label: t("markdown.fields.sourceWarehouse"),
      accessorKey: "sourceWarehouseLabel",
      dataType: "reference",
      sourceType: "lookup",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 190,
      minSize: 180,
      maxSize: 360,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "enum",
      formatKind: "plain",
    },
    {
      id: "targetWarehouseLabel",
      label: t("markdown.fields.targetWarehouse"),
      accessorKey: "targetWarehouseLabel",
      dataType: "reference",
      sourceType: "lookup",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 200,
      minSize: 180,
      maxSize: 360,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "enum",
      formatKind: "plain",
    },
    {
      id: "lineCount",
      label: t("markdown.fields.lineCount"),
      accessorKey: "lineCount",
      dataType: "number",
      sourceType: "derived",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 100,
      minSize: 90,
      maxSize: 160,
      rendererType: "numeric",
      performanceCost: "low",
      filterKind: "number",
      formatKind: "plain",
      cellDataType: true,
    },
    {
      id: "totalQty",
      label: t("markdown.fields.totalQty"),
      accessorKey: "totalQty",
      dataType: "number",
      sourceType: "derived",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 120,
      minSize: 110,
      maxSize: 180,
      rendererType: "numeric",
      performanceCost: "low",
      filterKind: "number",
      formatKind: "plain",
      cellDataType: true,
    },
    {
      id: "createdAt",
      label: t("markdown.fields.createdAt"),
      accessorKey: "createdAt",
      dataType: "datetime",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 200,
      minSize: 180,
      maxSize: 280,
      rendererType: "date",
      performanceCost: "low",
      filterKind: "datetime",
      formatKind: "plain",
    },
    {
      id: "postedAt",
      label: t("markdown.fields.postedAt"),
      accessorKey: "postedAt",
      dataType: "datetime",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 200,
      minSize: 180,
      maxSize: 280,
      rendererType: "date",
      performanceCost: "low",
      filterKind: "datetime",
      formatKind: "plain",
    },
  ];
}

export function buildMarkdownCodesTableSchema(input: { t: TFunction }): MarkdownJournalTanstackColumnSchema[] {
  const { t } = input;
  return [
    {
      id: "lineNo",
      label: t("doc.columns.lineNo"),
      dataType: "identifier",
      sourceType: "system",
      defaultVisible: true,
      lockedVisible: true,
      sortable: false,
      filterable: false,
      exportable: true,
      selectable: true,
      defaultSize: 56,
      minSize: 56,
      maxSize: 56,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "none",
    },
    {
      id: "markdownCode",
      label: t("markdown.fields.markdownCode"),
      accessorKey: "markdownCode",
      dataType: "identifier",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 150,
      minSize: 140,
      maxSize: 220,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
      formatKind: "plain",
    },
    {
      id: "journalNumber",
      label: t("markdown.fields.journalNumber"),
      accessorKey: "journalNumber",
      dataType: "identifier",
      sourceType: "lookup",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 150,
      minSize: 140,
      maxSize: 220,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
      formatKind: "plain",
    },
    {
      id: "itemCode",
      label: t("doc.columns.itemCode"),
      accessorKey: "itemCode",
      dataType: "identifier",
      sourceType: "lookup",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 120,
      minSize: 110,
      maxSize: 200,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
      formatKind: "plain",
    },
    {
      id: "itemName",
      label: t("doc.columns.itemName"),
      accessorKey: "itemName",
      dataType: "string",
      sourceType: "lookup",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 240,
      minSize: 220,
      maxSize: 560,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
      formatKind: "plain",
    },
    {
      id: "quantity",
      label: t("doc.columns.qty"),
      accessorKey: "quantity",
      dataType: "number",
      sourceType: "derived",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 90,
      minSize: 80,
      maxSize: 140,
      rendererType: "numeric",
      performanceCost: "low",
      filterKind: "number",
      formatKind: "plain",
      cellDataType: true,
    },
    {
      id: "markdownPrice",
      label: t("markdown.fields.markdownPrice"),
      accessorKey: "markdownPrice",
      dataType: "money",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 140,
      minSize: 130,
      maxSize: 200,
      rendererType: "numeric",
      performanceCost: "low",
      filterKind: "number",
      formatKind: "markdown-price",
      cellDataType: true,
    },
    {
      id: "warehouseLabel",
      label: t("markdown.fields.targetWarehouse"),
      accessorKey: "warehouseLabel",
      dataType: "reference",
      sourceType: "lookup",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 180,
      minSize: 160,
      maxSize: 360,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "enum",
      formatKind: "plain",
    },
    {
      id: "statusLabel",
      label: t("common.status"),
      accessorKey: "statusLabel",
      dataType: "enum",
      sourceType: "derived",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 130,
      minSize: 120,
      maxSize: 220,
      rendererType: "status-badge",
      performanceCost: "low",
      filterKind: "enum",
      formatKind: "plain",
    },
    {
      id: "reasonLabel",
      label: t("markdown.fields.reason"),
      accessorKey: "reasonLabel",
      dataType: "enum",
      sourceType: "derived",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 220,
      minSize: 180,
      maxSize: 400,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "enum",
      formatKind: "plain",
    },
    {
      id: "postedAt",
      label: t("markdown.fields.postedAt"),
      accessorKey: "postedAt",
      dataType: "datetime",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 200,
      minSize: 180,
      maxSize: 280,
      rendererType: "date",
      performanceCost: "low",
      filterKind: "datetime",
      formatKind: "plain",
    },
  ];
}
