import type { LabelTemplate } from "../model";

const now = () => new Date().toISOString();

/**
 * Three built-in templates for first-run seed. Not print-ready artwork — valid structural placeholders.
 */
export function buildDefaultLabelTemplates(): LabelTemplate[] {
  const t = now();
  return [
    {
      id: "label-tpl-sys-item",
      name: "Товарная этикетка",
      description: "Наименование, код и основной штрихкод.",
      kind: "ITEM_LABEL",
      paperType: "LABEL",
      sizeMm: { width: 58, height: 40 },
      isActive: true,
      isDefault: true,
      isArchived: false,
      isSystem: true,
      tags: ["system", "builtin"],
      createdAt: t,
      updatedAt: t,
      elements: [
        {
          id: "el-title",
          type: "text",
          xMm: 2,
          yMm: 4,
          widthMm: 54,
          heightMm: 8,
          binding: { kind: "field", path: "item.name" },
          style: { fontSizeMm: 2.8, fontWeight: "bold", textAlign: "left" },
        },
        {
          id: "el-code",
          type: "text",
          xMm: 2,
          yMm: 13,
          widthMm: 54,
          heightMm: 5,
          binding: { kind: "field", path: "item.code" },
          style: { fontSizeMm: 2.2, textAlign: "left" },
        },
        {
          id: "el-bc",
          type: "barcode",
          xMm: 4,
          yMm: 20,
          widthMm: 50,
          heightMm: 14,
          binding: { kind: "primary_barcode" },
          options: { showHumanReadableText: true },
        },
      ],
    },
    {
      id: "label-tpl-sys-price",
      name: "Ценник",
      description: "Название и цена продажи.",
      kind: "PRICE_TAG",
      paperType: "LABEL",
      sizeMm: { width: 50, height: 30 },
      isActive: true,
      isDefault: false,
      isArchived: false,
      isSystem: true,
      tags: ["system", "builtin"],
      createdAt: t,
      updatedAt: t,
      elements: [
        {
          id: "el-name",
          type: "text",
          xMm: 2,
          yMm: 3,
          widthMm: 46,
          heightMm: 8,
          binding: { kind: "field", path: "item.name" },
          style: { fontSizeMm: 2.4, fontWeight: "bold", textAlign: "center" },
        },
        {
          id: "el-price",
          type: "text",
          xMm: 2,
          yMm: 12,
          widthMm: 46,
          heightMm: 10,
          binding: { kind: "field", path: "item.salePrice" },
          style: { fontSizeMm: 4, fontWeight: "bold", textAlign: "center" },
        },
        {
          id: "el-border",
          type: "shape",
          xMm: 0.5,
          yMm: 0.5,
          widthMm: 49,
          heightMm: 29,
          shapeKind: "rect",
          style: { strokeMm: 0.2, stroke: "#333333" },
        },
      ],
    },
    {
      id: "label-tpl-sys-qr",
      name: "QR-наклейка",
      description: "Компактный QR по основному штрихкоду.",
      kind: "QR_LABEL",
      paperType: "LABEL",
      sizeMm: { width: 25, height: 25 },
      isActive: true,
      isDefault: false,
      isArchived: false,
      isSystem: true,
      tags: ["system", "builtin"],
      createdAt: t,
      updatedAt: t,
      elements: [
        {
          id: "el-qr",
          type: "qr",
          xMm: 3,
          yMm: 3,
          widthMm: 19,
          heightMm: 19,
          binding: { kind: "primary_barcode" },
          options: { errorCorrection: "M" },
        },
      ],
    },
    {
      id: "label-tpl-sys-translation",
      name: "Переводной стикер",
      description: "Локализованное название, код, основной ШК.",
      kind: "TRANSLATION_STICKER",
      paperType: "LABEL",
      sizeMm: { width: 58, height: 45 },
      isActive: true,
      isDefault: false,
      isArchived: false,
      isSystem: true,
      tags: ["system", "builtin", "translation"],
      createdAt: t,
      updatedAt: t,
      elements: [
        {
          id: "tr-title",
          type: "text",
          xMm: 2,
          yMm: 3,
          widthMm: 54,
          heightMm: 8,
          binding: { kind: "field", path: "item.translationName" },
          style: { fontSizeMm: 2.8, fontWeight: "bold", textAlign: "left" },
        },
        {
          id: "tr-original",
          type: "text",
          xMm: 2,
          yMm: 11,
          widthMm: 54,
          heightMm: 5,
          binding: { kind: "field", path: "item.name" },
          style: { fontSizeMm: 1.9, textAlign: "left" },
        },
        {
          id: "tr-code",
          type: "text",
          xMm: 2,
          yMm: 16,
          widthMm: 54,
          heightMm: 4,
          binding: { kind: "field", path: "item.code" },
          style: { fontSizeMm: 2, textAlign: "left" },
        },
        {
          id: "tr-bc",
          type: "barcode",
          xMm: 4,
          yMm: 22,
          widthMm: 50,
          heightMm: 14,
          binding: { kind: "primary_barcode" },
          options: { showHumanReadableText: true, symbologyHint: "CODE_128" },
        },
        {
          id: "tr-note",
          type: "text",
          xMm: 2,
          yMm: 37,
          widthMm: 54,
          heightMm: 6,
          binding: { kind: "field", path: "item.translationDescription" },
          style: { fontSizeMm: 1.8, textAlign: "left" },
        },
      ],
    },
    {
      id: "label-tpl-sys-kiz",
      name: "КИЗ / маркировка",
      description: "DataMatrix по коду маркировки, КИЗ, код номенклатуры. Данные справочные.",
      kind: "KIZ_LABEL",
      paperType: "LABEL",
      sizeMm: { width: 58, height: 50 },
      isActive: true,
      isDefault: false,
      isArchived: false,
      isSystem: true,
      tags: ["system", "builtin", "marking"],
      createdAt: t,
      updatedAt: t,
      elements: [
        {
          id: "kz-hint",
          type: "text",
          xMm: 2,
          yMm: 2,
          widthMm: 54,
          heightMm: 4,
          text: "Маркировка (справочно, не юр. подтверждение)",
          style: { fontSizeMm: 1.6, textAlign: "center" },
        },
        {
          id: "kz-name",
          type: "text",
          xMm: 2,
          yMm: 7,
          widthMm: 36,
          heightMm: 8,
          binding: { kind: "field", path: "item.name" },
          style: { fontSizeMm: 2.2, fontWeight: "bold", textAlign: "left" },
        },
        {
          id: "kz-code",
          type: "text",
          xMm: 2,
          yMm: 15,
          widthMm: 36,
          heightMm: 4,
          binding: { kind: "field", path: "item.code" },
          style: { fontSizeMm: 2, textAlign: "left" },
        },
        {
          id: "kz-kiz",
          type: "text",
          xMm: 2,
          yMm: 19,
          widthMm: 36,
          heightMm: 4,
          binding: { kind: "field", path: "item.kizCode" },
          style: { fontSizeMm: 1.8, textAlign: "left" },
        },
        {
          id: "kz-dm",
          type: "barcode",
          xMm: 40,
          yMm: 6,
          widthMm: 16,
          heightMm: 16,
          binding: { kind: "field", path: "item.gs1DataMatrixPayload" },
          options: { symbologyHint: "GS1_DATAMATRIX", showHumanReadableText: false },
        },
        {
          id: "kz-bc128",
          type: "barcode",
          xMm: 2,
          yMm: 28,
          widthMm: 54,
          heightMm: 12,
          binding: { kind: "primary_barcode" },
          options: { symbologyHint: "CODE_128", showHumanReadableText: true },
        },
      ],
    },
    {
      id: "label-tpl-sys-datamatrix",
      name: "DataMatrix этикетка",
      description: "Название, код, DataMatrix по полю dataMatrixPayload (или общий markingCode в проверках).",
      kind: "DATAMATRIX_LABEL",
      paperType: "LABEL",
      sizeMm: { width: 50, height: 40 },
      isActive: true,
      isDefault: false,
      isArchived: false,
      isSystem: true,
      tags: ["system", "builtin", "datamatrix"],
      createdAt: t,
      updatedAt: t,
      elements: [
        {
          id: "dm-title",
          type: "text",
          xMm: 2,
          yMm: 3,
          widthMm: 30,
          heightMm: 10,
          binding: { kind: "field", path: "item.name" },
          style: { fontSizeMm: 2.4, fontWeight: "bold", textAlign: "left" },
        },
        {
          id: "dm-code",
          type: "text",
          xMm: 2,
          yMm: 13,
          widthMm: 30,
          heightMm: 5,
          binding: { kind: "field", path: "item.code" },
          style: { fontSizeMm: 2, textAlign: "left" },
        },
        {
          id: "dm-matrix",
          type: "barcode",
          xMm: 34,
          yMm: 3,
          widthMm: 14,
          heightMm: 14,
          binding: { kind: "field", path: "item.dataMatrixPayload" },
          options: { symbologyHint: "DATAMATRIX", showHumanReadableText: false },
        },
        {
          id: "dm-linear",
          type: "barcode",
          xMm: 2,
          yMm: 22,
          widthMm: 46,
          heightMm: 12,
          binding: { kind: "primary_barcode" },
          options: { symbologyHint: "CODE_128", showHumanReadableText: true },
        },
      ],
    },
  ];
}
