/**
 * Demo seed items (in-memory shape). Used when no items.json exists or after corrupt backup.
 * Brand/category ids come from seeded brand/category repositories.
 */
import { brandRepository } from "../brands/repository";
import { categoryRepository } from "../categories/repository";
import type { Item } from "./model";

function brandByCode(): Record<string, string> {
  const map: Record<string, string> = {};
  brandRepository.list().forEach((b) => {
    map[b.code] = b.id;
  });
  return map;
}

function categoryByCode(): Record<string, string> {
  const map: Record<string, string> = {};
  categoryRepository.list().forEach((c) => {
    map[c.code] = c.id;
  });
  return map;
}

/** Full {@link Item} rows with sequential string ids — same catalog as legacy in-repo seed. */
export function buildSeedItems(): Item[] {
  const b = brandByCode();
  const c = categoryByCode();
  const rows: Omit<Item, "id">[] = [
    {
      code: "ITEM-001",
      name: "Widget A",
      uom: "EA",
      isActive: true,
      brandId: b["ACME"],
      categoryId: c["COMPONENTS"],
      barcode: "5901234123457",
      purchasePrice: 4.5,
      salePrice: 7.99,
      images: [],
    },
    {
      code: "ITEM-002",
      name: "Widget B",
      uom: "EA",
      isActive: true,
      brandId: b["ACME"],
      categoryId: c["COMPONENTS"],
      barcode: "5901234123458",
      purchasePrice: 5.2,
      salePrice: 9.5,
      images: [],
    },
    {
      code: "ITEM-003",
      name: "Steel Bracket 50mm",
      uom: "EA",
      isActive: true,
      brandId: b["METALWORKS"],
      categoryId: c["HARDWARE"],
      barcode: "5901234123459",
      purchasePrice: 2.1,
      salePrice: 3.5,
      images: [],
    },
    {
      code: "ITEM-004",
      name: "Aluminum Channel 1m",
      uom: "EA",
      isActive: true,
      brandId: b["METALWORKS"],
      categoryId: c["HARDWARE"],
      barcode: "5901234123460",
      purchasePrice: 12,
      salePrice: 18,
      images: [],
    },
    {
      code: "ITEM-005",
      name: "Assembly Kit Type A",
      uom: "BOX",
      isActive: true,
      brandId: b["ACME"],
      categoryId: c["KITS"],
      barcode: "5901234123461",
      purchasePrice: 25,
      salePrice: 39,
      images: [],
    },
    {
      code: "ITEM-006",
      name: "Assembly Kit Type B",
      uom: "BOX",
      isActive: true,
      brandId: b["ACME"],
      categoryId: c["KITS"],
      barcode: "5901234123462",
      purchasePrice: 32,
      salePrice: 49,
      images: [],
    },
    {
      code: "ITEM-007",
      name: "O-Ring Set 10pc",
      uom: "PK",
      isActive: true,
      brandId: b["SEALPRO"],
      categoryId: c["SEALS"],
      barcode: "5901234123463",
      purchasePrice: 3.5,
      salePrice: 5.5,
      images: [],
    },
    {
      code: "ITEM-008",
      name: "Gasket Sheet 1m²",
      uom: "EA",
      isActive: true,
      brandId: b["SEALPRO"],
      categoryId: c["SEALS"],
      barcode: "5901234123464",
      purchasePrice: 18,
      salePrice: 28,
      images: [],
    },
    {
      code: "ITEM-009",
      name: "Fastener M6x20",
      uom: "PK",
      isActive: true,
      brandId: b["BOLTCO"],
      categoryId: c["FASTENERS"],
      barcode: "5901234123465",
      purchasePrice: 2.8,
      salePrice: 4.2,
      images: [],
    },
    {
      code: "ITEM-010",
      name: "Fastener M8x25",
      uom: "PK",
      isActive: true,
      brandId: b["BOLTCO"],
      categoryId: c["FASTENERS"],
      barcode: "5901234123466",
      purchasePrice: 3.5,
      salePrice: 5.5,
      images: [],
    },
    {
      code: "ITEM-011",
      name: "Grease Cartridge 400g",
      uom: "EA",
      isActive: true,
      brandId: b["LUBEMAX"],
      categoryId: c["CONSUMABLES"],
      barcode: "5901234123467",
      purchasePrice: 6,
      salePrice: 9.5,
      images: [],
    },
    {
      code: "ITEM-012",
      name: "Coolant 5L",
      uom: "EA",
      isActive: true,
      brandId: b["LUBEMAX"],
      categoryId: c["CONSUMABLES"],
      barcode: "5901234123468",
      purchasePrice: 22,
      salePrice: 35,
      images: [],
    },
    {
      code: "ITEM-013",
      name: "Filter Element Air",
      uom: "EA",
      isActive: true,
      brandId: b["FILTERTECH"],
      categoryId: c["FILTERS"],
      barcode: "5901234123469",
      purchasePrice: 8,
      salePrice: 14,
      images: [],
    },
    {
      code: "ITEM-014",
      name: "Filter Element Oil",
      uom: "EA",
      isActive: true,
      brandId: b["FILTERTECH"],
      categoryId: c["FILTERS"],
      barcode: "5901234123470",
      purchasePrice: 9,
      salePrice: 15,
      images: [],
    },
    {
      code: "ITEM-015",
      name: "Drive Belt V-Type",
      uom: "EA",
      isActive: true,
      brandId: b["DRIVEPARTS"],
      categoryId: c["TRANSMISSION"],
      barcode: "5901234123471",
      purchasePrice: 15,
      salePrice: 24,
      images: [],
    },
    {
      code: "ITEM-016",
      name: "Seal Kit Standard",
      uom: "BOX",
      isActive: true,
      brandId: b["SEALPRO"],
      categoryId: c["SEALS"],
      barcode: "5901234123472",
      purchasePrice: 45,
      salePrice: 69,
      images: [],
    },
    {
      code: "ITEM-017",
      name: "Control Board Rev.2",
      uom: "EA",
      isActive: true,
      brandId: b["ELECTROLOGIC"],
      categoryId: c["ELECTRONICS"],
      barcode: "5901234123473",
      purchasePrice: 85,
      salePrice: 129,
      images: [],
    },
    {
      code: "ITEM-018",
      name: "Sensor Proximity 24V",
      uom: "EA",
      isActive: true,
      brandId: b["ELECTROLOGIC"],
      categoryId: c["SENSORS"],
      barcode: "5901234123474",
      purchasePrice: 28,
      salePrice: 42,
      images: [],
    },
    {
      code: "ITEM-019",
      name: "Cable Assembly 2m",
      uom: "EA",
      isActive: true,
      brandId: b["ELECTROLOGIC"],
      categoryId: c["CABLES"],
      barcode: "5901234123475",
      purchasePrice: 12,
      salePrice: 19,
      images: [],
    },
    {
      code: "ITEM-020",
      name: 'Display Unit 7"',
      uom: "EA",
      isActive: true,
      brandId: b["DISPLAYTECH"],
      categoryId: c["ELECTRONICS"],
      barcode: "5901234123476",
      purchasePrice: 55,
      salePrice: 89,
      images: [],
    },
    {
      code: "ITEM-021",
      name: "Spacer Ring 12mm",
      uom: "PK",
      isActive: true,
      brandId: b["BOLTCO"],
      categoryId: c["HARDWARE"],
      barcode: "5901234123477",
      purchasePrice: 1.5,
      salePrice: 2.5,
      images: [],
    },
    {
      code: "ITEM-022",
      name: "Washer M10",
      uom: "PK",
      isActive: true,
      brandId: b["BOLTCO"],
      categoryId: c["FASTENERS"],
      barcode: "5901234123478",
      purchasePrice: 0.8,
      salePrice: 1.5,
      images: [],
    },
    {
      code: "ITEM-023",
      name: "Legacy Adapter Plate",
      uom: "EA",
      isActive: false,
      brandId: b["METALWORKS"],
      categoryId: c["HARDWARE"],
      barcode: "5901234123479",
      purchasePrice: 20,
      salePrice: 0,
      images: [],
    },
    {
      code: "ITEM-024",
      name: "Obsolete Gasket Old",
      uom: "EA",
      isActive: false,
      brandId: b["SEALPRO"],
      categoryId: c["SEALS"],
      purchasePrice: 5,
      salePrice: 0,
      images: [],
    },
    {
      code: "ITEM-025",
      name: "Spare Parts Kit Basic",
      uom: "CTN",
      isActive: true,
      brandId: b["ACME"],
      categoryId: c["KITS"],
      barcode: "5901234123480",
      purchasePrice: 60,
      salePrice: 95,
      images: [],
    },
  ];

  let n = 1;
  return rows.map((row) => ({ ...row, id: String(n++) }));
}
