import { brandRepository } from "@/modules/brands/repository";
import { categoryRepository } from "@/modules/categories/repository";
import type { TFunction } from "@/shared/i18n";
import type {
  ListViewFieldDataType,
} from "@/shared/ui/ag-grid/listViewConfig";
import type {
  ListViewFieldSourceType,
  ListViewPerformanceCost,
  ListViewRendererType,
} from "@/shared/ui/ag-grid/listViewConfig/types";
import type { ItemListRow } from "./listViewRowModel";

export type ItemsTableFilterKind = "text" | "number" | "enum" | "boolean" | "none";
export type ItemsTableFormatKind = "none" | "money" | "yes-no" | "item-kind";

export type ItemsTableOption = {
  value: string;
  label: string;
};

export type ItemsTableColumnSchema = {
  id: string;
  label: string;
  accessorKey?: keyof ItemListRow;
  dataType: ListViewFieldDataType;
  sourceType: ListViewFieldSourceType;
  defaultVisible: boolean;
  lockedVisible: boolean;
  sortable: boolean;
  filterable: boolean;
  exportable: boolean;
  selectable: boolean;
  defaultSize?: number;
  minSize?: number;
  maxSize?: number;
  defaultFlex?: number;
  rendererType: ListViewRendererType;
  performanceCost: ListViewPerformanceCost;
  filterKind: ItemsTableFilterKind;
  formatKind?: ItemsTableFormatKind;
  enumOptions?: ItemsTableOption[];
  cellDataType?: boolean;
};

type BuildItemsTableSchemaInput = {
  t: TFunction;
};

export function buildItemsTableSchema(input: BuildItemsTableSchemaInput): ItemsTableColumnSchema[] {
  const { t } = input;
  return [
    {
      id: "lineNo",
      label: t("doc.columns.lineNo"),
      dataType: "identifier",
      sourceType: "system",
      defaultVisible: true,
      lockedVisible: true,
      sortable: false,
      filterable: false,
      exportable: true,
      selectable: true,
      defaultSize: 56,
      minSize: 56,
      maxSize: 56,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "none",
    },
    {
      id: "code",
      label: t("doc.columns.code"),
      accessorKey: "code",
      dataType: "identifier",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 130,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
    },
    {
      id: "itemKind",
      label: t("master.item.list.kindColumn"),
      accessorKey: "itemKind",
      dataType: "enum",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 100,
      maxSize: 120,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "enum",
      formatKind: "item-kind",
      enumOptions: [
        { value: "SELLABLE", label: t("master.item.kind.sellable") },
        { value: "TESTER", label: t("master.item.kind.tester") },
      ],
    },
    {
      id: "name",
      label: t("doc.columns.name"),
      accessorKey: "name",
      dataType: "string",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      minSize: 160,
      defaultFlex: 1,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
    },
    {
      id: "imageCount",
      label: t("doc.columns.images"),
      accessorKey: "imageCount",
      dataType: "number",
      sourceType: "derived",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 76,
      maxSize: 88,
      rendererType: "numeric",
      performanceCost: "low",
      filterKind: "number",
    },
    {
      id: "hasImages",
      label: t("doc.columns.hasImages"),
      accessorKey: "hasImages",
      dataType: "boolean",
      sourceType: "derived",
      defaultVisible: false,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 120,
      rendererType: "boolean-badge",
      performanceCost: "low",
      filterKind: "boolean",
      formatKind: "yes-no",
      cellDataType: false,
    },
    {
      id: "brand",
      label: t("doc.columns.brand"),
      accessorKey: "brand",
      dataType: "reference",
      sourceType: "lookup",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 110,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "enum",
      enumOptions: brandRepository.list().map((brand) => ({ value: brand.name, label: brand.name })),
    },
    {
      id: "category",
      label: t("doc.columns.category"),
      accessorKey: "category",
      dataType: "reference",
      sourceType: "lookup",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 120,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "enum",
      enumOptions: categoryRepository.list().map((category) => ({ value: category.name, label: category.name })),
    },
    {
      id: "uom",
      label: t("doc.columns.uom"),
      accessorKey: "uom",
      dataType: "string",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 90,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
    },
    {
      id: "purchasePrice",
      label: t("doc.columns.purchasePrice"),
      accessorKey: "purchasePrice",
      dataType: "money",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 120,
      rendererType: "numeric",
      performanceCost: "medium",
      filterKind: "number",
      formatKind: "money",
    },
    {
      id: "salePrice",
      label: t("doc.columns.salePrice"),
      accessorKey: "salePrice",
      dataType: "money",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 100,
      rendererType: "numeric",
      performanceCost: "medium",
      filterKind: "number",
      formatKind: "money",
    },
    {
      id: "isActive",
      label: t("doc.columns.active"),
      accessorKey: "isActive",
      dataType: "boolean",
      sourceType: "document",
      defaultVisible: true,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 100,
      rendererType: "boolean-badge",
      performanceCost: "low",
      filterKind: "boolean",
      formatKind: "yes-no",
      cellDataType: false,
    },
    {
      id: "description",
      label: t("common.description"),
      accessorKey: "description",
      dataType: "string",
      sourceType: "document",
      defaultVisible: false,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      minSize: 180,
      defaultSize: 220,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
    },
    {
      id: "barcode",
      label: t("doc.columns.primaryBarcode"),
      accessorKey: "barcode",
      dataType: "identifier",
      sourceType: "derived",
      defaultVisible: false,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 150,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
    },
    {
      id: "barcodeCount",
      label: t("doc.columns.barcodeCount"),
      accessorKey: "barcodeCount",
      dataType: "number",
      sourceType: "derived",
      defaultVisible: false,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 120,
      rendererType: "numeric",
      performanceCost: "low",
      filterKind: "number",
    },
    {
      id: "hasBarcode",
      label: t("doc.columns.hasBarcode"),
      accessorKey: "hasBarcode",
      dataType: "boolean",
      sourceType: "derived",
      defaultVisible: false,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 110,
      rendererType: "boolean-badge",
      performanceCost: "low",
      filterKind: "boolean",
      formatKind: "yes-no",
      cellDataType: false,
    },
    {
      id: "accountingProfile",
      label: t("master.item.accountingProfile"),
      accessorKey: "accountingProfile",
      dataType: "string",
      sourceType: "document",
      defaultVisible: false,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 170,
      rendererType: "text",
      performanceCost: "low",
      filterKind: "text",
    },
    {
      id: "testerCount",
      label: t("doc.columns.testerCount"),
      accessorKey: "testerCount",
      dataType: "number",
      sourceType: "derived",
      defaultVisible: false,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 120,
      rendererType: "numeric",
      performanceCost: "low",
      filterKind: "number",
    },
    {
      id: "hasTesters",
      label: t("doc.columns.hasTesters"),
      accessorKey: "hasTesters",
      dataType: "boolean",
      sourceType: "derived",
      defaultVisible: false,
      lockedVisible: false,
      sortable: true,
      filterable: true,
      exportable: true,
      selectable: true,
      defaultSize: 120,
      rendererType: "boolean-badge",
      performanceCost: "low",
      filterKind: "boolean",
      formatKind: "yes-no",
      cellDataType: false,
    },
  ];
}
