import type { ListViewEntityType, ListViewFieldRegistryEntry } from "./types";

const ITEMS_FIELDS: ListViewFieldRegistryEntry[] = [
  {
    fieldKey: "lineNo",
    entityType: "items",
    label: "№",
    dataType: "identifier",
    sourceType: "system",
    defaultVisible: true,
    lockedVisible: true,
    sortable: false,
    filterable: false,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "code",
    entityType: "items",
    label: "Code",
    dataType: "identifier",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "itemKind",
    entityType: "items",
    label: "Kind",
    dataType: "enum",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "name",
    entityType: "items",
    label: "Name",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "imageCount",
    entityType: "items",
    label: "Images",
    dataType: "number",
    sourceType: "derived",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "numeric",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "brand",
    entityType: "items",
    label: "Brand",
    dataType: "reference",
    sourceType: "lookup",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "category",
    entityType: "items",
    label: "Category",
    dataType: "reference",
    sourceType: "lookup",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "uom",
    entityType: "items",
    label: "UOM",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "purchasePrice",
    entityType: "items",
    label: "Purchase price",
    dataType: "money",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "numeric",
    requiresPermission: null,
    performanceCost: "medium",
  },
  {
    fieldKey: "salePrice",
    entityType: "items",
    label: "Sale price",
    dataType: "money",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "numeric",
    requiresPermission: null,
    performanceCost: "medium",
  },
  {
    fieldKey: "isActive",
    entityType: "items",
    label: "Active",
    dataType: "boolean",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "boolean-badge",
    requiresPermission: null,
    performanceCost: "low",
  },
];

const SALES_ORDER_FIELDS: ListViewFieldRegistryEntry[] = [
  {
    fieldKey: "lineNo",
    entityType: "sales-orders",
    label: "№",
    dataType: "identifier",
    sourceType: "system",
    defaultVisible: true,
    lockedVisible: true,
    sortable: false,
    filterable: false,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "number",
    entityType: "sales-orders",
    label: "Number",
    dataType: "identifier",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "date",
    entityType: "sales-orders",
    label: "Date",
    dataType: "date",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "date",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "customerName",
    entityType: "sales-orders",
    label: "Customer",
    dataType: "reference",
    sourceType: "lookup",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "warehouseName",
    entityType: "sales-orders",
    label: "Warehouse",
    dataType: "reference",
    sourceType: "lookup",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "carrierLabel",
    entityType: "sales-orders",
    label: "Carrier",
    dataType: "reference",
    sourceType: "derived",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "recipientLabel",
    entityType: "sales-orders",
    label: "Recipient",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "recipientPhoneLabel",
    entityType: "sales-orders",
    label: "Recipient phone",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "status",
    entityType: "sales-orders",
    label: "Status",
    dataType: "enum",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "status-badge",
    requiresPermission: null,
    performanceCost: "low",
  },
];

const PURCHASE_ORDER_FIELDS: ListViewFieldRegistryEntry[] = [
  {
    fieldKey: "lineNo",
    entityType: "purchase-orders",
    label: "№",
    dataType: "identifier",
    sourceType: "system",
    defaultVisible: true,
    lockedVisible: true,
    sortable: false,
    filterable: false,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "number",
    entityType: "purchase-orders",
    label: "Number",
    dataType: "identifier",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "date",
    entityType: "purchase-orders",
    label: "Date",
    dataType: "date",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "date",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "supplierName",
    entityType: "purchase-orders",
    label: "Supplier",
    dataType: "reference",
    sourceType: "lookup",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "warehouseName",
    entityType: "purchase-orders",
    label: "Warehouse",
    dataType: "reference",
    sourceType: "lookup",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "status",
    entityType: "purchase-orders",
    label: "Status",
    dataType: "enum",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "status-badge",
    requiresPermission: null,
    performanceCost: "low",
  },
];

const RECEIPT_FIELDS: ListViewFieldRegistryEntry[] = [
  {
    fieldKey: "lineNo",
    entityType: "receipts",
    label: "№",
    dataType: "identifier",
    sourceType: "system",
    defaultVisible: true,
    lockedVisible: true,
    sortable: false,
    filterable: false,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "number",
    entityType: "receipts",
    label: "Number",
    dataType: "identifier",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "date",
    entityType: "receipts",
    label: "Date",
    dataType: "date",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "date",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "purchaseOrderNumber",
    entityType: "receipts",
    label: "Purchase order",
    dataType: "identifier",
    sourceType: "lookup",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "warehouseName",
    entityType: "receipts",
    label: "Warehouse",
    dataType: "reference",
    sourceType: "lookup",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "status",
    entityType: "receipts",
    label: "Status",
    dataType: "enum",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "status-badge",
    requiresPermission: null,
    performanceCost: "low",
  },
];

const SHIPMENT_FIELDS: ListViewFieldRegistryEntry[] = [
  {
    fieldKey: "lineNo",
    entityType: "shipments",
    label: "№",
    dataType: "identifier",
    sourceType: "system",
    defaultVisible: true,
    lockedVisible: true,
    sortable: false,
    filterable: false,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "number",
    entityType: "shipments",
    label: "Number",
    dataType: "identifier",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "date",
    entityType: "shipments",
    label: "Date",
    dataType: "date",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "date",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "salesOrderNumber",
    entityType: "shipments",
    label: "Sales order",
    dataType: "identifier",
    sourceType: "lookup",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "warehouseName",
    entityType: "shipments",
    label: "Warehouse",
    dataType: "reference",
    sourceType: "lookup",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "carrierLabel",
    entityType: "shipments",
    label: "Carrier",
    dataType: "reference",
    sourceType: "derived",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "trackingLabel",
    entityType: "shipments",
    label: "Tracking number",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "recipientLabel",
    entityType: "shipments",
    label: "Recipient",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "recipientPhoneLabel",
    entityType: "shipments",
    label: "Recipient phone",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "deliveryAddressPreview",
    entityType: "shipments",
    label: "Delivery address",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "status",
    entityType: "shipments",
    label: "Status",
    dataType: "enum",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "status-badge",
    requiresPermission: null,
    performanceCost: "low",
  },
];

const STOCK_BALANCE_FIELDS: ListViewFieldRegistryEntry[] = [
  {
    fieldKey: "lineNo",
    entityType: "stock-balances",
    label: "№",
    dataType: "identifier",
    sourceType: "system",
    defaultVisible: true,
    lockedVisible: true,
    sortable: false,
    filterable: false,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "itemCode",
    entityType: "stock-balances",
    label: "Item code",
    dataType: "identifier",
    sourceType: "lookup",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "itemName",
    entityType: "stock-balances",
    label: "Item name",
    dataType: "string",
    sourceType: "lookup",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "warehouseName",
    entityType: "stock-balances",
    label: "Warehouse",
    dataType: "reference",
    sourceType: "lookup",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "style",
    entityType: "stock-balances",
    label: "Style",
    dataType: "enum",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "qtyOnHand",
    entityType: "stock-balances",
    label: "Total quantity",
    dataType: "number",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "numeric",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "reservedQty",
    entityType: "stock-balances",
    label: "Reserved",
    dataType: "number",
    sourceType: "derived",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "numeric",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "availableQty",
    entityType: "stock-balances",
    label: "Available",
    dataType: "number",
    sourceType: "derived",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "numeric",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "deficitQty",
    entityType: "stock-balances",
    label: "Deficit",
    dataType: "number",
    sourceType: "derived",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "numeric",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "outgoingQty",
    entityType: "stock-balances",
    label: "Outgoing",
    dataType: "number",
    sourceType: "derived",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "numeric",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "incomingQty",
    entityType: "stock-balances",
    label: "Incoming",
    dataType: "number",
    sourceType: "derived",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "numeric",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "netShortageQty",
    entityType: "stock-balances",
    label: "Net shortage",
    dataType: "number",
    sourceType: "derived",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "numeric",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "coverageStatus",
    entityType: "stock-balances",
    label: "Coverage",
    dataType: "enum",
    sourceType: "derived",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "status-badge",
    requiresPermission: null,
    performanceCost: "low",
  },
];

const STOCK_MOVEMENT_FIELDS: ListViewFieldRegistryEntry[] = [
  {
    fieldKey: "lineNo",
    entityType: "stock-movements",
    label: "№",
    dataType: "identifier",
    sourceType: "system",
    defaultVisible: true,
    lockedVisible: true,
    sortable: false,
    filterable: false,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "datetime",
    entityType: "stock-movements",
    label: "Date time",
    dataType: "datetime",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "date",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "movementType",
    entityType: "stock-movements",
    label: "Movement type",
    dataType: "enum",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "status-badge",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "itemCode",
    entityType: "stock-movements",
    label: "Item code",
    dataType: "identifier",
    sourceType: "lookup",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "itemName",
    entityType: "stock-movements",
    label: "Item name",
    dataType: "string",
    sourceType: "lookup",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "warehouseName",
    entityType: "stock-movements",
    label: "Warehouse",
    dataType: "reference",
    sourceType: "lookup",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "qtyDelta",
    entityType: "stock-movements",
    label: "Qty delta",
    dataType: "number",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "numeric",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "sourceDocumentLabel",
    entityType: "stock-movements",
    label: "Source document",
    dataType: "identifier",
    sourceType: "lookup",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "relatedOrder",
    entityType: "stock-movements",
    label: "Related order",
    dataType: "identifier",
    sourceType: "derived",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
];

const CUSTOMER_FIELDS: ListViewFieldRegistryEntry[] = [
  {
    fieldKey: "lineNo",
    entityType: "customers",
    label: "№",
    dataType: "identifier",
    sourceType: "system",
    defaultVisible: true,
    lockedVisible: true,
    sortable: false,
    filterable: false,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "code",
    entityType: "customers",
    label: "Code",
    dataType: "identifier",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "name",
    entityType: "customers",
    label: "Name",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "contactPerson",
    entityType: "customers",
    label: "Contact person",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "phone",
    entityType: "customers",
    label: "Phone",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "email",
    entityType: "customers",
    label: "Email",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "city",
    entityType: "customers",
    label: "City",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "paymentTermsDays",
    entityType: "customers",
    label: "Payment terms",
    dataType: "number",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "numeric",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "isActive",
    entityType: "customers",
    label: "Active",
    dataType: "boolean",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "boolean-badge",
    requiresPermission: null,
    performanceCost: "low",
  },
];

const SUPPLIER_FIELDS: ListViewFieldRegistryEntry[] = [
  {
    fieldKey: "lineNo",
    entityType: "suppliers",
    label: "№",
    dataType: "identifier",
    sourceType: "system",
    defaultVisible: true,
    lockedVisible: true,
    sortable: false,
    filterable: false,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "code",
    entityType: "suppliers",
    label: "Code",
    dataType: "identifier",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "name",
    entityType: "suppliers",
    label: "Name",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "contactPerson",
    entityType: "suppliers",
    label: "Contact person",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "phone",
    entityType: "suppliers",
    label: "Phone",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "email",
    entityType: "suppliers",
    label: "Email",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "city",
    entityType: "suppliers",
    label: "City",
    dataType: "string",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "text",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "paymentTermsDays",
    entityType: "suppliers",
    label: "Payment terms",
    dataType: "number",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "numeric",
    requiresPermission: null,
    performanceCost: "low",
  },
  {
    fieldKey: "isActive",
    entityType: "suppliers",
    label: "Active",
    dataType: "boolean",
    sourceType: "document",
    defaultVisible: true,
    lockedVisible: false,
    sortable: true,
    filterable: true,
    exportable: true,
    selectable: true,
    rendererType: "boolean-badge",
    requiresPermission: null,
    performanceCost: "low",
  },
];

const REGISTRY: Record<ListViewEntityType, ListViewFieldRegistryEntry[]> = {
  items: ITEMS_FIELDS,
  "sales-orders": SALES_ORDER_FIELDS,
  "purchase-orders": PURCHASE_ORDER_FIELDS,
  receipts: RECEIPT_FIELDS,
  shipments: SHIPMENT_FIELDS,
  "stock-balances": STOCK_BALANCE_FIELDS,
  "stock-movements": STOCK_MOVEMENT_FIELDS,
  customers: CUSTOMER_FIELDS,
  suppliers: SUPPLIER_FIELDS,
};

export function getListViewFieldRegistry(entityType: ListViewEntityType): ListViewFieldRegistryEntry[] {
  return REGISTRY[entityType];
}
